language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - nosetests --with-coverage # Add me to run nose with coverage
after_success:
  - coveralls
